apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ template "openldap.fullname" . }}
  labels:
    {{- include "openldap.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "openldap.selectorLabels" . | nindent 6 }}
